_target_: myria3d.pctl.datamodule.hdf5.HDF5LidarDataModule

# A standalone precomputed HDF5 dataset can be used without source files by setting data_dir and split_csv_path to null.
data_dir: ${hydra:runtime.cwd}/data  # data directory containing LAS files
epsg: 2154
split_csv_path: ${hydra:runtime.cwd}/data/dfc2019_dataset_split.csv  # csv specifying split, with schema basename, split (where split is one out of train/val/test)
hdf5_file_path: ${hydra:runtime.cwd}/data/hdf5_dfc2019.hdf5  # where to create a HDF5 dataset file from LAS and CSV sources.

# functions used to load and preprocess LAS data points into a pytorch geometric Data object.
points_pre_transform:
  _target_: functools.partial
  _args_:
    - "${get_method:myria3d.pctl.points_pre_transform.dfc2019.dfc2019_pre_transform}"

pre_filter:
  _target_: functools.partial
  _args_: 
    - "${get_method:myria3d.pctl.dataset.utils.pre_filter_below_n_points}"
  min_num_nodes: 1

tile_width: 500
subtile_width: 50
subtile_overlap_train: 0
subtile_overlap_predict: "${predict.subtile_overlap}"

batch_size: 32
num_workers: 3
prefetch_factor: 3

defaults:
  - transforms: default.yaml
